export const GET_QUESTION_REQUEST = "GET_QUESTION_REQUEST";
export const GET_QUESTION_SUCCESS = "GET_QUESTION_SUCCESS";
export const GET_QUESTION_FAIL = "GET_QUESTION_FAIL";

export const ADD_ANSWER_SUCCESS = "ADD_ANSWER_SUCCESS";
export const ADD_ANSWER_FAILURE = "ADD_ANSWER_FAILURE";

export const VOTE_QUESTION_SUCCESS = "VOTE_QUESTION_SUCCESS";
export const VOTE_ANSWER_SUCCESS = "VOTE_ANSWER_SUCCESS";
export const VOTE_FAILED = "VOTE_FAILED";
export const MARK_ANSWER_BEST = "MARK_ANSWER_BEST";

export const SET_ANSWER_COUNT = "SET_ANSWER_COUNT";

export const GET_ANSWERS_REQUEST = "GET_ANSWERS_REQUEST";
export const GET_ANSWERS_SUCCESS = "GET_ANSWERS_SUCCESS";
export const GET_ANSWERS_FAIL = "GET_ANSWERS_FAIL";
export const SET_ANSWERS_PAGE = "SET_ANSWERS_PAGE";

export const RESET_QUESTION = "RESET_QUESTION";
