export const GET_QUESTIONS_REQUEST = "GET_QUESTIONS_REQUEST";
export const GET_QUESTIONS_SUCCESS = "GET_QUESTIONS_SUCCESS";
export const GET_QUESTIONS_FAIL = "GET_QUESTIONS_FAIL";

export const SEARCH_QUESTION_SUCCESS = "SEARCH_QUESTION_SUCCESS";
export const SEARCH_QUESTION_FAILURE = "SEARCH_QUESTION_FAILURE";
export const CREATE_QUESTION_SUCCESS = "CREATE_QUESTION_SUCCESS";
export const CREATE_QUESTION_FAILURE = "CREATE_QUESTION_FAILURE";

export const SET_QUESTION_COUNT = "SET_QUESTION_COUNT";

export const RESET_QUESTIONS = "RESET_QUESTIONS";
