export const GET_QUESTIONS_SUCCESS = "GET_QUESTIONS_SUCCESS";
export const GET_QUESTIONS_FAIL = "GET_QUESTIONS_FAIL";
export const GET_QUESTION_SUCCESS = "GET_QUESTIONS_FAIL";
export const GET_QUESTION_FAIL = "GET_QUESTIONS_FAIL";
