export const GET_QUESTIONS_SUCCESS = "GET_QUESTIONS_SUCCESS";
export const GET_QUESTIONS_FAIL = "GET_QUESTIONS_FAIL";
export const GET_QUESTION_SUCCESS = "GET_QUESTION_SUCCESS";
export const GET_QUESTION_FAIL = "GET_QUESTION_FAIL";
export const VOTE_QUESTION_SUCCESS = "VOTE_QUESTION_SUCCESS";
export const VOTE_ANSWER_SUCCESS = "VOTE_ANSWER_SUCCESS";
export const VOTE_FAILED = "VOTE_FAILED";
